package hello;

import java.util.concurrent.atomic.AtomicLong;

import hello.entities.Game;
import hello.repositories.GameRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
public class GreetingController {

    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();

    @Autowired // This means to get the bean called gameRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GameRepository gameRepository;

    @RequestMapping("/greeting")
    public Greeting greeting(@RequestParam(value="name", defaultValue="World") String name) {
        return new Greeting(counter.incrementAndGet(),
                            String.format(template, name));
    }
}
